language: ruby
cache:
- apt
- bundler
git:
  submodules: false
rvm:
  - 2.1.3
env:
  - TAG=import
  - TAG=export
script: "bundle exec rake test[$FEATURE]"
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs npm firefox
  - npm update
