pref('extensions.zotero.translators.better-bibtex.citeCommand', 'cite')
pref('extensions.zotero.translators.better-bibtex.citeKeyFormat', '[auth][year]')
pref('extensions.zotero.translators.better-bibtex.unicode', '')
pref('extensions.zotero.translators.better-bibtex.fancyURLs', false)
pref('extensions.zotero.translators.better-bibtex.brace-all', true)
pref('extensions.zotero.translators.better-bibtex.useprefix', false)
pref('extensions.zotero.translators.better-bibtex.skipfields', '')
pref('extensions.zotero.translators.better-bibtex.langid', 'babel')
pref('extensions.zotero.translators.better-bibtex.auto-abbrev.style', '')
pref('extensions.zotero.translators.better-bibtex.auto-abbrev', true)
pref('extensions.zotero.translators.better-bibtex.attachmentRelativePath', false)
pref('extensions.zotero.translators.better-bibtex.testmode', false)
pref('extensions.zotero.translators.better-bibtex.pin-citekeys', 'manual')
pref('extensions.zotero.translators.better-bibtex.scan-citekeys', true)
pref('extensions.zotero.translators.better-bibtex.raw-imports', false)
pref('extensions.zotero.translators.better-bibtex.show-citekey', false)
pref('extensions.zotero.translators.better-bibtex.key-conflict-policy', 'keep')
pref('extensions.zotero.translators.better-bibtex.doi-and-url', 'both')

# debugging prefs
pref("browser.dom.window.dump.enabled", true)
pref("javascript.options.showInConsole", true)
pref("javascript.options.strict", true)
pref("nglayout.debug.disable_xul_cache", true)
pref("nglayout.debug.disable_xul_fastload", true)
pref("devtools.debugger.remote-enabled", true)